---
title: "story_danica_ann"
output: html_document
---

We kicked off this class by defining what data journalism meant to us. My idea of data journalism has for a long time been limited to a simple chart of information yet there is a need for contextualization when producing these simplified charts. 

Data journalist,Mona Chalabi, uses hand-drawn sketches and simple imagery to break down complex data on issues(as all data journalists should). I think it's amazing how drawings are more effective than a statistical report of numbers as it eliminates a language barrier and in turn people of all backgrounds have access to the same knowledge! In this article, I was particularly drawn to her mention of representation in data journalism. Data is only compelling to people when they can see themselves in the data or how it impacts them. She mentions how her experiences influence what news she decides to report on. To eliminate the possibility of misconceptions in her work  ,she takes deliberate steps to ask people around her what they find important and uses that to find and report what is actually current and relevant. 

Reading this article and watching her walk through her creative process has made me think of how I can make conscious efforts providing representation of my audience in my data reporting to add a relational element for my readers to connect to. 
